name: On Pull request

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  buildAndRunForSomeVersions:
    name: Run tests for ${{ matrix.minecraftVersion }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[release]')"
    strategy:
      fail-fast: false
      matrix:
        minecraftVersion:
          - latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
