name: On Push

on:
  push:
    branches: [ master ]

jobs:
  build_run_publish:
    name: Run tests for ${{ matrix.minecraftVersion }} and Release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    strategy:
      fail-fast: false
      matrix:
        minecraftVersion:
          - latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
      - name: Upload to Bintray and CurseForge
        run: ./gradlew clean bintrayUpload curseforge
        env:
          BINTRAY_USER: catcore
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          CURSEKEY: ${{ secrets.CURSEKEY }}
